name: 'deploy'

on:
    push:
        branches:
            - 'main'

jobs:
    build:
        name: 'Deploy'
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"

            - name: "Setup node"
              uses: "actions/setup-node@v4"
              with:
                  node-version: 18
          
            - name: "Build"
              run: |
                  yarn
                  yarn build

            - name: "Deploy to GitHub Pages"
              if: success()
              uses: crazy-max/ghaction-github-pages@v4
              with:
                target_branch: gh-pages
                build_dir: dist
                jekyll: false
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

